const projects=[...Array(50)].map((_,i)=>({id:i+1,name:['Expanding Cards','Progress Steps','Rotating Navigation','Hidden Search','Blurry Loading','Scroll Animation','Split Landing Page','Form Wave','Sound Board','Dad Jokes','Event Keycodes','FAQ Collapse','Random Choice Picker','Animated Navigation','Incrementing Counter','Drink Water','Movie App','Background Slider','Theme Clock','Button Ripple Effect','Drag N Drop','Drawing App','Kinetic Loader','Content Placeholder','Sticky Navbar','Double Vertical Slider','Toast Notification','Github Profiles','Double Click Heart','Auto Text Effect','Password Generator','Good Cheap Fast','Notes App','Animated Countdown','Image Carousel','Hoverboard','Pokedex','Mobile Tab Navigation','Password Strength','3D Background Boxes','Verify Account UI','Live User Filter','Feedback UI','Custom Range Slider','Netflix Navigation','Quiz App','Testimonial Switcher','Random Image Feed','Todo List','Insect Catch Game'][i],category:['UI','Interaction','Animation','Apps'][i%4],slug:String(i+1).padStart(2,'0')}));
const systems=[
['shell','Shell','Processes · pipes · commands'],['hash-table','Hash Table','Hashing · collisions'],['tiny-database','Tiny Database','Pages · B-tree · storage'],['tiny-compiler','Tiny Compiler','Lexer · parser · AST'],['virtual-machine','Virtual Machine','Bytecode · stack'],['memory-allocator','Memory Allocator','Heap · free blocks'],['http-server','HTTP Server','Requests · responses'],['tcp-chat-server','TCP Chat Server','Sockets · clients'],['redis-clone','Redis Clone','RESP · persistence'],['chip8-emulator','CHIP-8 Emulator','CPU · memory · display'],['text-editor','Text Editor','Buffer · cursor'],['tiny-raytracer','Tiny Raytracer','Rays · intersections'],['mini-kernel','Mini Kernel','Boot · kernel flow']
].map(([slug,name,description],i)=>({id:'sys-'+slug,slug,name,description,category:'Systems',kind:'system'}));
const all=[...projects,...systems],$=s=>document.querySelector(s),grid=$('#grid');
let filter='All',search='';
function card(p){
 if(p.kind==='system')return `<article class="card system-card"><div class="system-mark">C/C++</div><div class="card-body"><small>SYSTEMS LAB · ${p.description}</small><h2>${p.name}</h2><p>Native source project with an interactive architecture explainer.</p><div><button class="open" data-open="${p.id}">Explore →</button><a href="https://github.com/nestlir/nestlir/tree/main/projects/project-based-learning/c-cpp/${p.slug}" target="_blank">Native source ↗</a></div></div></article>`;
 return `<article class="card"><div class="thumb" style="--n:${p.id}" data-open="${p.id}"><span>#${String(p.id).padStart(2,'0')}</span></div><div class="card-body"><small>FRONTEND LAB · ${p.category}</small><h2>${p.name}</h2><div><button class="open" data-open="${p.id}">Open →</button><a href="./projects/${p.slug}/index.html">Project ↗</a></div></div></article>`;
}
function render(){const q=search.toLowerCase();const list=all.filter(p=>(filter==='All'||(filter==='Frontend'? !p.kind:p.kind))&&p.name.toLowerCase().includes(q));grid.innerHTML=list.map(card).join('');$('#count').textContent=`${list.length} projects`;document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(b.dataset.open));}
function open(id){const p=all.find(x=>String(x.id)===String(id));if(!p)return;if(!p.kind){location.href=`./projects/${p.slug}/index.html`;return;}$('#catalog').hidden=true;$('#app').innerHTML=`<section class="demo"><header><button id="back">← Lab</button><span>C/C++ SYSTEMS LAB</span><a target="_blank" href="https://github.com/nestlir/nestlir/tree/main/projects/project-based-learning/c-cpp/${p.slug}">Native source ↗</a></header><div class="demo-head"><small>NATIVE PROJECT + INTERACTIVE EXPLAINER</small><h1>${p.name}</h1><p>${p.description}. The visualization explains concepts and does not pretend to execute the C/C++ binary.</p></div><div class="stage" id="stage"></div></section>`;$('#back').onclick=()=>{$('#app').innerHTML='';$('#catalog').hidden=false};systemDemo(p);}
function systemDemo(p){const s=$('#stage');const diagrams={shell:'INPUT → PARSER → FORK → EXEC → PROCESS', 'hash-table':'KEY → HASH(key) → BUCKET → VALUE','tiny-database':'QUERY → PARSER → EXECUTOR → B-TREE → PAGE','tiny-compiler':'SOURCE → TOKENS → AST → BYTECODE','virtual-machine':'BYTECODE → FETCH → DECODE → STACK','memory-allocator':'REQUEST → HEAP → BLOCK → FREE LIST','http-server':'CLIENT → SOCKET → REQUEST → RESPONSE','tcp-chat-server':'CLIENT A ↔ SERVER ↔ CLIENT B','redis-clone':'COMMAND → PARSER → STORE → PERSISTENCE','chip8-emulator':'ROM → FETCH → DECODE → REGISTERS → DISPLAY','text-editor':'INPUT → BUFFER → CURSOR → RENDER','tiny-raytracer':'RAY → INTERSECTION → NORMAL → PIXEL','mini-kernel':'BOOT → INIT → MEMORY → SCHEDULER'};s.innerHTML=`<div class="architecture"><div class="diagram">${diagrams[p.slug]||p.description}</div><button id="step">Run one visual step</button><div id="state">Ready</div></div>`;let n=0;$('#step').onclick=()=>{$('#state').textContent=['Input accepted','Stage 1 complete','State updated','Pipeline complete'][n++%4];s.classList.toggle('go');};}
$('#search').oninput=e=>{search=e.target.value;render()};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});render();