const projects=[
{id:'datavac',name:'DataVac',kind:'frontend',tags:['Next.js','TypeScript','API'],image:'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=1400&q=85',role:'Frontend · API integration · forms · payments · PDF · E2E',text:'Информационный продукт с каталогом, поиском, фильтрацией и API-интеграцией.',repo:'https://github.com/DataVac-masterskaya/data-vac-frontend'},
{id:'furniture',name:'Furniture Store',kind:'frontend',tags:['HTML','SCSS','JavaScript'],image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1400&q=85',role:'Product UI · responsive · SEO · seller dashboard',text:'Премиальный мебельный шоурум с каталогом, фильтрами и демо-кабинетом продавца.',repo:'https://github.com/nestlir/Furniture_Store_Ru'},
{id:'storyos',name:'Story OS',kind:'ai fullstack',tags:['Python','Telegram','OpenAI'],image:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=85',role:'AI product · bot UX · persistence · analytics',text:'AI-ассистент для структурирования миров, персонажей и сюжетных линий.',repo:'https://github.com/nestlir/story-os-bot-1.0'},
{id:'multimodal',name:'Multimodal AI',kind:'ai fullstack',tags:['Python','React','Docker'],image:'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1400&q=85',role:'Architecture · API gateway · services · AI integrations',text:'Мультимодальное приложение для текста, голоса и изображений.',repo:'https://github.com/nestlir/multimodal-ai-app'},
{id:'burger',name:'Stellar Burger',kind:'frontend',tags:['React','Redux','API'],image:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1400&q=85',role:'React UI · state · routing · API',text:'Приложение для заказа бургеров с авторизацией и личным кабинетом.',repo:'https://github.com/nestlir/stellar-burger'},
{id:'larek',name:'Web Larek',kind:'fullstack',tags:['TypeScript','Express','MongoDB'],image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1400&q=85',role:'Frontend · API contract · e-commerce flows',text:'E-commerce приложение с frontend, backend и административными сценариями.',repo:'https://github.com/nestlir/web-larek-frontend'}
];
const translations={ru:{eyebrow:'FRONTEND · PRODUCT · VISUALS',title:'Digital products<br><em>with a pulse.</em>',intro:'Создаю интерфейсы, которые хочется рассматривать и которыми приятно пользоваться. Люблю React, TypeScript, продуктовую логику и немного сладкого хаоса.',cta:'Смотреть проекты ↗',projectsTitle:'Проекты',projectsLead:'Карточки открываются в полноценный popup: изображение, роль, стек, задача и ссылка на код.',manifesto:'Характер — это не шум.<br><em>Это способ запомниться.</em>',manifestoText:'Текстуры, фотографии, маркеры, стикеры, anime mood и pop-culture существуют здесь не ради украшения. Они помогают продукту иметь голос.',skillsTitle:'Что у меня в арсенале',contactTitle:'Есть идея?<br><em>Давайте сделаем.</em>',contactText:'Открыта к frontend, product и full-stack задачам.'},en:{eyebrow:'FRONTEND · PRODUCT · VISUALS',title:'Digital products<br><em>with a pulse.</em>',intro:'I build interfaces people want to look at and enjoy using. React, TypeScript, product logic and a little sweet chaos.',cta:'View projects ↗',projectsTitle:'Projects',projectsLead:'Cards open into a full popup with image, role, stack, scope and repository.',manifesto:'Character is not noise.<br><em>It is how you get remembered.</em>',manifestoText:'Textures, photography, markers, stickers, anime mood and pop culture are here to give the product a voice.',skillsTitle:'What is in my toolbox',contactTitle:'Have an idea?<br><em>Let’s make it.</em>',contactText:'Open to frontend, product and full-stack work.'}};
let lang=localStorage.getItem('colorful-lang')||'ru';let filter='all';
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function renderText(){const d=translations[lang];$$('[data-i]').forEach(el=>{const key=el.dataset.i;if(d[key])el.innerHTML=d[key]});$$('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));}
function renderProjects(){const items=projects.filter(p=>filter==='all'||p.kind.includes(filter));$('#projectGrid').innerHTML=items.map((p,i)=>`<article class="project" data-kind="${p.kind}"><button class="project-open" data-id="${p.id}"><figure><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="frame">FRAME ${String(i+1).padStart(2,'0')}</span><span class="sticker">✦</span></figure><div class="project-content"><small>${p.kind.toUpperCase()}</small><h3>${p.name} <b>↗</b></h3><p>${p.text}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><em>${p.role}</em></div></button></article>`).join('');$$('.project-open').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.id)));}
function openProject(id){const p=projects.find(x=>x.id===id);$('#modalBody').innerHTML=`<img class="modal-image" src="${p.image}" alt="${p.name}"><div class="modal-copy"><small>SELECTED WORK / ${p.kind.toUpperCase()}</small><h2>${p.name}</h2><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><h3>My contribution</h3><p>${p.role}</p><h3>About</h3><p>${p.text}</p><a class="primary" href="${p.repo}" target="_blank" rel="noreferrer">Open repository ↗</a></div>`;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false');document.body.classList.add('modal-open');}
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');}
$$('[data-lang]').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;localStorage.setItem('colorful-lang',lang);renderText();}));
$$('.filters button').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;$$('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProjects();}));
$('#close').addEventListener('click',closeModal);$('.backdrop').addEventListener('click',closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
$('#theme').addEventListener('click',()=>document.body.classList.toggle('dark'));
window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;$('#progress').style.width=`${h>0?scrollY/h*100:0}%`;});
window.addEventListener('pointermove',e=>{const c=$('#cursor');c.style.left=e.clientX+'px';c.style.top=e.clientY+'px';});
renderText();renderProjects();