const projects = [
  {name:'DataVac', type:'frontend product', tags:['Next.js','TypeScript','Tailwind'], image:'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=1200&q=85', text:{ru:'Информационный продукт с поиском, фильтрацией, API-интеграцией, каталогом вакцин, платежным сценарием и генерацией PDF.',en:'Information product with search, filtering, API integration, vaccine catalog, payments and PDF generation.',ja:'検索・フィルター・API連携・ワクチンカタログ・決済・PDF生成を備えた情報プロダクト。'}, detail:{ru:'Командный frontend-проект: реальные API, mapper-логика, сложные таблицы, поиск, фильтры, CloudPayments, PDF и E2E.',en:'Team frontend project with real APIs, mapper logic, complex tables, search, filters, CloudPayments, PDF and E2E.',ja:'実API、mapperロジック、複雑なテーブル、検索、フィルター、CloudPayments、PDF、E2Eを扱うチーム開発。'}, repo:'https://github.com/DataVac-masterskaya/data-vac-frontend'},
  {name:'Furniture Store', type:'frontend product', tags:['HTML','SCSS','JavaScript'], image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=85', text:{ru:'Премиальный мебельный шоурум с каталогом, фильтрами, заявкой покупателя и демо-кабинетом продавца.',en:'Premium furniture showroom with catalog, filters, lead form and a demo seller dashboard.',ja:'カタログ、フィルター、問い合わせフォーム、販売員向けデモ画面を備えた家具ショールーム。'}, detail:{ru:'Самостоятельный product-style кейс с responsive UI, SEO, Schema.org, GitHub Pages и локальным MVP кабинета продавца.',en:'Independent product-style case with responsive UI, SEO, Schema.org, GitHub Pages and a local seller-dashboard MVP.',ja:'レスポンシブUI、SEO、Schema.org、GitHub Pages、販売員ダッシュボードMVPを含む個人プロジェクト。'}, repo:'https://github.com/nestlir/Furniture_Store_Ru'},
  {name:'Story OS', type:'fullstack ai', tags:['Python','Telegram','OpenAI'], image:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=85', text:{ru:'AI-ассистент для структурирования вымышленных миров, персонажей, событий и сюжетных линий.',en:'AI assistant for structuring fictional worlds, characters, events and storylines.',ja:'架空の世界、キャラクター、出来事、ストーリーを整理するAIアシスタント。'}, detail:{ru:'Продуктовый AI-кейс: Telegram-first интерфейс, SQLite persistence, аналитический слой и дисциплина FACT / INFERENCE / SUGGESTION.',en:'Product AI case with Telegram-first UX, SQLite persistence, an analytics layer and FACT / INFERENCE / SUGGESTION discipline.',ja:'Telegram中心のUX、SQLite永続化、分析レイヤー、FACT / INFERENCE / SUGGESTIONの設計規律を持つAIプロダクト。'}, repo:'https://github.com/nestlir/story-os-bot-1.0'},
  {name:'Multimodal AI', type:'fullstack ai', tags:['Python','React','Docker'], image:'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=85', text:{ru:'Мультимодальное приложение для обработки текста, голоса и изображений через набор сервисов.',en:'Multimodal application for text, voice and image processing across multiple services.',ja:'複数サービスを通じてテキスト、音声、画像を処理するマルチモーダルアプリ。'}, detail:{ru:'Архитектурный кейс с microservices, API gateway, Redis, Docker/Kubernetes и несколькими AI-провайдерами.',en:'Architecture case using microservices, an API gateway, Redis, Docker/Kubernetes and multiple AI providers.',ja:'マイクロサービス、API Gateway、Redis、Docker/Kubernetes、複数AIプロバイダーを使ったアーキテクチャケース。'}, repo:'https://github.com/nestlir/multimodal-ai-app'},
  {name:'Stellar Burger', type:'frontend', tags:['React','Redux','API'], image:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=85', text:{ru:'Приложение для заказа бургеров с авторизацией, конструктором и личным кабинетом.',en:'Burger ordering application with authentication, constructor and personal account.',ja:'認証、バーガーコンストラクター、個人アカウントを備えた注文アプリ。'}, detail:{ru:'React application с глобальным состоянием, маршрутизацией, API и пользовательскими сценариями заказа.',en:'React application with global state, routing, API integration and ordering flows.',ja:'グローバル状態、ルーティング、API連携、注文フローを備えたReactアプリ。'}, repo:'https://github.com/nestlir/stellar-burger'},
  {name:'Web Larek', type:'fullstack', tags:['TypeScript','Express','MongoDB'], image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=85', text:{ru:'E-commerce приложение с frontend, backend и административными сценариями.',en:'E-commerce application with frontend, backend and administrative flows.',ja:'フロントエンド、バックエンド、管理者フローを備えたE-commerceアプリ。'}, detail:{ru:'Кейс, показывающий TypeScript frontend, API-взаимодействие и понимание full-stack границы приложения.',en:'Case demonstrating TypeScript frontend engineering, API communication and full-stack boundaries.',ja:'TypeScriptフロントエンド、API通信、フルスタック境界への理解を示すケース。'}, repo:'https://github.com/nestlir/web-larek-frontend'},
  {name:'Mesto', type:'frontend', tags:['React','REST API','CSS'], image:'https://images.unsplash.com/photo-1516321165247-4aa89a48be28?auto=format&fit=crop&w=1200&q=85', text:{ru:'Социальный интерфейс с профилем, карточками, лайками и модальными сценариями.',en:'Social interface with profile, cards, likes and modal flows.',ja:'プロフィール、カード、いいね、モーダル操作を備えたソーシャルUI。'}, detail:{ru:'Практика React state, controlled forms, REST API и декомпозиции интерфейса.',en:'Practice with React state, controlled forms, REST API and interface decomposition.',ja:'React state、controlled forms、REST API、UI分解を実践したケース。'}, repo:'https://github.com/nestlir/mesto-project-ff'},
  {name:'Blog Customizer', type:'frontend', tags:['React','TypeScript','Forms'], image:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=85', text:{ru:'Конфигурируемый интерфейс статьи с настройкой визуальных параметров.',en:'Configurable article interface with adjustable visual parameters.',ja:'ビジュアルパラメータを変更できるカスタマイズ可能な記事UI。'}, detail:{ru:'Кейс на state modeling, формы, reusable UI и управляемые настройки отображения.',en:'Case focused on state modeling, forms, reusable UI and controlled display settings.',ja:'state modeling、フォーム、再利用可能UI、表示設定を扱うケース。'}, repo:'https://github.com/nestlir/blog-customizer'},
  {name:'Оно тебе надо', type:'frontend', tags:['HTML','CSS','Responsive'], image:'https://images.unsplash.com/photo-1455885666463-19c48e1a9a39?auto=format&fit=crop&w=1200&q=85', text:{ru:'Editorial landing page с акцентом на типографику, композицию и адаптивность.',en:'Editorial landing page focused on typography, composition and responsive layout.',ja:'タイポグラフィ、構成、レスポンシブレイアウトを重視したEditorial landing page。'}, detail:{ru:'Frontend fundamentals: semantic HTML, Grid/Flexbox и pixel-accurate responsive layout.',en:'Frontend fundamentals: semantic HTML, Grid/Flexbox and pixel-accurate responsive layout.',ja:'semantic HTML、Grid/Flexbox、精密なレスポンシブレイアウトを実践。'}, repo:'https://github.com/nestlir/ono-tebe-nado'}
];

const translations = {
  ru:{nav:{about:'Обо мне',projects:'Проекты',skills:'Навыки',experience:'Опыт',contact:'Контакты'},hero:{eyebrow:'Frontend · Product · UX · a little chaos',title:'Анастасия<br><em>Frontend Developer</em>',text:'Собираю интерфейсы, которые хочется рассматривать. Превращаю данные, идеи и сложные сценарии в живые digital-продукты.',cta:'Смотреть проекты <span>↗</span>',scroll:'↓ scroll to enter the portfolio'},about:{label:'01 / About the character',title:'Разрабатываю интерфейсы, которыми <em>приятно пользоваться.</em>',p1:'Мой основной фокус — frontend-разработка на React и TypeScript. Но я люблю смотреть шире кода: на историю пользователя, атмосферу продукта, визуальный ритм и то, что остаётся в памяти после взаимодействия.',p2:'Поэтому в моих проектах рядом существуют API, компоненты, анимации, Figma, AI, странные идеи и аккуратная инженерия.',stat1:'product thinking',stat2:'visual systems',stat3:'engineering'},projects:{label:'02 / Selected work',title:'Проекты',lead:'Продуктовые интерфейсы, AI, full-stack эксперименты и frontend-кейсы — без скучных презентаций.'},filter:{all:'Все',frontend:'Frontend',product:'Product',fullstack:'Full-stack',ai:'AI'},manifesto:{label:'03 / Visual manifesto',title:'Это то,<br>как продукт<br><em>разговаривает.</em>',text:'Я люблю интерфейсы с характером — но характер никогда не должен мешать пользователю.',side:'Текстуры, сладкие акценты, мемы, аниме-настроение и pop-culture — не ради шума, а чтобы создавать эмоциональную память.',quote:'cute, but make it functional.'},skills:{label:'04 / Skill tree',title:'Что у меня в арсенале',go1:'→ build the interface',go2:'→ shape the experience',go3:'→ make it work',go4:'→ break the box'},experience:{label:'05 / Behind the scenes',title:'От интерфейса<br>до <em>продукта.</em>',t1:'Командная разработка',p1:'Реальные API, UI, пользовательские сценарии, интеграции, code review и E2E-проверки.',t2:'Frontend engineering',p2:'Адаптивные интерфейсы, сложные таблицы, поиск, фильтрация, формы, платежи, PDF и reusable components.',t3:'Product mindset',p3:'Сначала понимаю историю пользователя и результат, затем выбираю технологию и форму.'},contact:{eyebrow:'Final scene / Contact',title:'Есть идея?<br><em>Давайте сделаем.</em>',text:'Открыта к frontend, product и full-stack задачам, где можно приносить пользу, экспериментировать и расти вместе с командой.',email:'Написать мне ↗'},footer:'Designed, coded & slightly overthought.',more:'Подробнее ↗',open:'Открыть репозиторий ↗',selected:'Selected project',close:'Закрыть'},
  en:{nav:{about:'About',projects:'Projects',skills:'Skills',experience:'Experience',contact:'Contact'},hero:{eyebrow:'Frontend · Product · UX · a little chaos',title:'Anastasia<br><em>Frontend Developer</em>',text:'I build interfaces people want to look at. Turning data, ideas and complex flows into living digital products.',cta:'View projects <span>↗</span>',scroll:'↓ scroll to enter the portfolio'},about:{label:'01 / About the character',title:'I build interfaces that are <em>pleasant to use.</em>',p1:'My main focus is frontend development with React and TypeScript. But I like looking beyond code: user stories, product atmosphere, visual rhythm and what remains after an interaction.',p2:'That is why APIs, components, animation, Figma, AI, strange ideas and careful engineering coexist in my projects.',stat1:'product thinking',stat2:'visual systems',stat3:'engineering'},projects:{label:'02 / Selected work',title:'Projects',lead:'Product interfaces, AI, full-stack experiments and frontend cases — without boring presentations.'},filter:{all:'All',frontend:'Frontend',product:'Product',fullstack:'Full-stack',ai:'AI'},manifesto:{label:'03 / Visual manifesto',title:'It is how<br>a product<br><em>speaks.</em>',text:'I like interfaces with character — but character should never get in the user’s way.',side:'Textures, sweet accents, memes, anime mood and pop culture — not for noise, but to create emotional memory.',quote:'cute, but make it functional.'},skills:{label:'04 / Skill tree',title:'What is in my arsenal',go1:'→ build the interface',go2:'→ shape the experience',go3:'→ make it work',go4:'→ break the box'},experience:{label:'05 / Behind the scenes',title:'From interface<br>to <em>product.</em>',t1:'Team development',p1:'Real APIs, UI, user flows, integrations, code review and E2E checks.',t2:'Frontend engineering',p2:'Responsive interfaces, complex tables, search, filtering, forms, payments, PDF and reusable components.',t3:'Product mindset',p3:'I understand the user story and outcome first, then choose the technology and form.'},contact:{eyebrow:'Final scene / Contact',title:'Have an idea?<br><em>Let’s make it.</em>',text:'Open to frontend, product and full-stack work where I can contribute, experiment and grow with a team.',email:'Write to me ↗'},footer:'Designed, coded & slightly overthought.',more:'View project ↗',open:'Open repository ↗',selected:'Selected project',close:'Close'},
  ja:{nav:{about:'プロフィール',projects:'プロジェクト',skills:'スキル',experience:'経験',contact:'連絡先'},hero:{eyebrow:'Frontend · Product · UX · a little chaos',title:'アナスタシア<br><em>Frontend Developer</em>',text:'見ていて楽しく、使って気持ちいいインターフェースを作ります。データ、アイデア、複雑なフローを生きたデジタルプロダクトへ。',cta:'プロジェクトを見る <span>↗</span>',scroll:'↓ scroll to enter the portfolio'},about:{label:'01 / About the character',title:'使っていて<em>心地いい</em>インターフェースを。',p1:'ReactとTypeScriptを中心にフロントエンドを開発しています。コードだけでなく、ユーザーストーリー、プロダクトの空気感、ビジュアルのリズムまで考えます。',p2:'API、コンポーネント、アニメーション、Figma、AI、少し変なアイデア、そして丁寧なエンジニアリングを一つのプロダクトにまとめます。',stat1:'product thinking',stat2:'visual systems',stat3:'engineering'},projects:{label:'02 / Selected work',title:'プロジェクト',lead:'プロダクトUI、AI、フルスタック実験、フロントエンドケースを一つの世界観で。'},filter:{all:'すべて',frontend:'Frontend',product:'Product',fullstack:'Full-stack',ai:'AI'},manifesto:{label:'03 / Visual manifesto',title:'プロダクトが<br><em>語る</em>方法。',text:'個性のあるUIが好き。でも、個性がユーザーの邪魔になってはいけません。',side:'テクスチャ、甘いアクセント、ミーム、アニメ、ポップカルチャー。ノイズではなく、感情の記憶をつくるために使います。',quote:'かわいい。でも、ちゃんと機能する。'},skills:{label:'04 / Skill tree',title:'スキルのアーセナル',go1:'→ interfaceを作る',go2:'→ experienceを設計する',go3:'→ 動かす',go4:'→ 型を壊す'},experience:{label:'05 / Behind the scenes',title:'インターフェースから<br><em>プロダクトへ。</em>',t1:'チーム開発',p1:'実API、UI、ユーザーフロー、連携、コードレビュー、E2Eテスト。',t2:'Frontend engineering',p2:'レスポンシブUI、複雑なテーブル、検索、フィルター、フォーム、決済、PDF、再利用可能コンポーネント。',t3:'Product mindset',p3:'まずユーザーの物語と成果を理解し、その後で技術と形を選びます。'},contact:{eyebrow:'Final scene / Contact',title:'アイデアがありますか？<br><em>一緒に作りましょう。</em>',text:'Frontend、Product、Full-stackの仕事で、チームに貢献しながら実験と成長を続けたいです。',email:'メールを送る ↗'},footer:'Designed, coded & slightly overthought.',more:'詳細を見る ↗',open:'リポジトリを開く ↗',selected:'Selected project',close:'閉じる'}
};

let currentLang = localStorage.getItem('portfolio-lang') || 'ru';
const grid = document.getElementById('projectGrid');
const modal = document.getElementById('projectModal');
const modalContent = document.getElementById('modalContent');
const progress = document.getElementById('scrollProgress');
const glow = document.querySelector('.cursor-glow');
const cursorDot = document.querySelector('.cursor-dot');

function getPath(obj,key){return key.split('.').reduce((v,k)=>v?.[k],obj)}
function applyLanguage(lang){
  currentLang=translations[lang]?lang:'ru'; localStorage.setItem('portfolio-lang',currentLang); document.documentElement.lang=currentLang;
  document.querySelectorAll('[data-i18n]').forEach(el=>{const value=getPath(translations[currentLang],el.dataset.i18n); if(value!==undefined) el.textContent=value});
  document.querySelectorAll('[data-i18n-html]').forEach(el=>{const value=getPath(translations[currentLang],el.dataset.i18nHtml); if(value!==undefined) el.innerHTML=value});
  document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===currentLang));
  document.querySelector('.projects-section h2').innerHTML=translations[currentLang].projects.title+'<span class="tiny-spark">✦</span>';
  document.querySelectorAll('.project-link').forEach((b)=>b.textContent=translations[currentLang].projects.title==='Проекты'?translations.ru.more:translations[currentLang].more);
}
function render(filter='all'){
  const list=filter==='all'?projects:projects.filter(p=>p.type.includes(filter));
  grid.innerHTML=list.map((p,i)=>`<article class="project tilt-card" data-index="${projects.indexOf(p)}"><div class="project-visual"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="project-film">FRAME ${String(i+1).padStart(2,'0')}</span><span class="project-sticker">✦</span></div><div class="project-body"><span class="project-num">${String(i+1).padStart(2,'0')}</span><h3>${p.name}</h3><div class="tags">${p.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><p>${p.text[currentLang]}</p><button class="project-link" data-project="${projects.indexOf(p)}">${translations[currentLang].more}</button></div></article>`).join('');
  grid.querySelectorAll('[data-project]').forEach(btn=>btn.addEventListener('click',()=>openProject(Number(btn.dataset.project))));
  grid.querySelectorAll('.tilt-card').forEach(attachTilt);
}
function openProject(index){
  const p=projects[index];
  modalContent.innerHTML=`<div class="popup-image"><img src="${p.image}" alt="${p.name}"><span>SELECTED / ${String(index+1).padStart(2,'0')}</span></div><div class="popup-copy"><span class="eyebrow">${translations[currentLang].selected} / ${String(index+1).padStart(2,'0')}</span><h2>${p.name}</h2><div class="tags">${p.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><p>${p.detail[currentLang]}</p><a class="button" href="${p.repo}" target="_blank" rel="noreferrer">${translations[currentLang].open}</a></div>`;
  modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); document.body.classList.add('modal-open');
}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
function updateProgress(){const max=document.documentElement.scrollHeight-window.innerHeight;progress.style.width=`${max>0?(window.scrollY/max)*100:0}%`}
function attachTilt(el){el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();const x=((e.clientX-r.left)/r.width-.5)*5;const y=((e.clientY-r.top)/r.height-.5)*-5;el.style.transform=`perspective(900px) rotateX(${y}deg) rotateY(${x}deg) translateY(-6px)`});el.addEventListener('pointerleave',()=>el.style.transform='')}

document.querySelectorAll('.lang').forEach(btn=>btn.addEventListener('click',()=>{applyLanguage(btn.dataset.lang);render(document.querySelector('.filter.active')?.dataset.filter||'all')}));
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');render(btn.dataset.filter)}));
document.getElementById('modalClose').addEventListener('click',closeModal);
modal.querySelector('.modal-backdrop').addEventListener('click',closeModal);
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.getElementById('themeToggle').addEventListener('click',()=>document.body.classList.toggle('dark'));
document.getElementById('chaosToggle').addEventListener('click',e=>{const active=document.body.classList.toggle('chaos-mode');e.currentTarget.setAttribute('aria-pressed',String(active));e.currentTarget.textContent=active?'ENOUGH ✦':'MAKE IT WEIRD ✦'});
const menuToggle=document.getElementById('menuToggle'), mobileNav=document.getElementById('mobileNav');
function closeMenu(){document.body.classList.remove('menu-open');menuToggle.setAttribute('aria-expanded','false');mobileNav.setAttribute('aria-hidden','true')}
menuToggle.addEventListener('click',()=>{const open=document.body.classList.toggle('menu-open');menuToggle.setAttribute('aria-expanded',String(open));mobileNav.setAttribute('aria-hidden',String(!open))});
mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
window.addEventListener('scroll',updateProgress,{passive:true});
window.addEventListener('pointermove',e=>{if(glow){glow.style.left=`${e.clientX}px`;glow.style.top=`${e.clientY}px`}if(cursorDot){cursorDot.style.left=`${e.clientX}px`;cursorDot.style.top=`${e.clientY}px`}});

actionButtons();
function actionButtons(){document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
render(); applyLanguage(currentLang); updateProgress();
