import http from 'node:http';import {randomUUID} from 'node:crypto';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {dirname,resolve} from 'node:path';
const PORT=Number(process.env.PORT||8787),HOST=process.env.HOST||'0.0.0.0',ALLOWED_ORIGIN=process.env.CORS_ORIGIN||'*',DATA_FILE=resolve(process.env.MOMOHA_DATA_FILE||'./api/data/orders.json');
const MENU=[{id:'ramen',name:'Tokyo Ramen',price:980,category:'savory',description:'Rich broth · noodles · egg · nori',image:'/suwenku/assets/food.svg'},{id:'takoyaki',name:'Takoyaki',price:680,category:'street',description:'6 crispy octopus balls · bonito · sauce',image:'/suwenku/assets/news-2.svg'},{id:'daifuku',name:'Strawberry Daifuku',price:520,category:'sweet',description:'Soft mochi · fresh strawberry · cream',image:'/suwenku/assets/news-3.svg'}];
const orders=[],hits=new Map();const RATE_WINDOW=60_000,RATE_LIMIT=30;let saveQueue=Promise.resolve();
async function loadOrders(){try{const raw=await readFile(DATA_FILE,'utf8');const parsed=JSON.parse(raw);if(Array.isArray(parsed))orders.push(...parsed.slice(-500))}catch(error){if(error.code!=='ENOENT')console.error('Could not load orders:',error.message)}}
function persistOrders(){const snapshot=JSON.stringify(orders.slice(-500),null,2);saveQueue=saveQueue.then(async()=>{await mkdir(dirname(DATA_FILE),{recursive:true});await writeFile(DATA_FILE,snapshot+'\n','utf8')}).catch((error)=>console.error('Could not persist orders:',error.message));return saveQueue}
function sendJson(res,status,payload){const body=JSON.stringify(payload);res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','content-length':Buffer.byteLength(body),'access-control-allow-origin':ALLOWED_ORIGIN,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});res.end(body)}
function clientKey(req){const forwarded=req.headers['x-forwarded-for'];return(Array.isArray(forwarded)?forwarded[0]:forwarded?.split(',')[0])?.trim()||req.socket.remoteAddress||'unknown'}
function checkRateLimit(req){const key=clientKey(req),now=Date.now(),entry=hits.get(key);if(!entry||now-entry.start>=RATE_WINDOW){hits.set(key,{start:now,count:1});return true}entry.count+=1;return entry.count<=RATE_LIMIT}
function validateOrder(input){const item=MENU.find((entry)=>entry.id===input?.itemId),qty=Number(input?.qty);if(!item)return{ok:false,error:'Unknown menu item.'};if(!Number.isInteger(qty)||qty<1||qty>12)return{ok:false,error:'Quantity must be an integer from 1 to 12.'};return{ok:true,item,qty}}
function readBody(req,maxBytes=8000){return new Promise((resolveBody,reject)=>{let total=0,chunks=[];req.on('data',(chunk)=>{total+=chunk.length;if(total>maxBytes){reject(Object.assign(new Error('Payload too large'),{statusCode:413}));req.destroy();return}chunks.push(chunk)});req.on('end',()=>resolveBody(Buffer.concat(chunks).toString('utf8')));req.on('error',reject)})}
const server=http.createServer(async(req,res)=>{const requestId=randomUUID();if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':ALLOWED_ORIGIN,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});return res.end()}if(!checkRateLimit(req))return sendJson(res,429,{ok:false,error:{code:'RATE_LIMITED',message:'Too many requests.',requestId}});const url=new URL(req.url||'/',`http://${req.headers.host||`${HOST}:${PORT}`}`);if(req.method==='GET'&&url.pathname==='/api/health')return sendJson(res,200,{ok:true,service:'momoha-api',timestamp:new Date().toISOString(),orders:orders.length,requestId});if(req.method==='GET'&&url.pathname==='/api/menu')return sendJson(res,200,{ok:true,items:MENU,requestId});if(req.method==='GET'&&url.pathname==='/api/orders')return sendJson(res,200,{ok:true,orders:orders.slice(-50),requestId});if(req.method==='POST'&&url.pathname==='/api/orders'){try{const raw=await readBody(req);let input;try{input=JSON.parse(raw||'{}')}catch{return sendJson(res,400,{ok:false,error:{code:'INVALID_JSON',message:'Request body must be valid JSON.',requestId}})}const result=validateOrder(input);if(!result.ok)return sendJson(res,400,{ok:false,error:{code:'VALIDATION_ERROR',message:result.error,requestId}});const order={id:`MM-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`,itemId:result.item.id,item:result.item.name,qty:result.qty,unitPrice:result.item.price,total:result.item.price*result.qty,createdAt:new Date().toISOString()};orders.push(order);if(orders.length>500)orders.shift();await persistOrders();return sendJson(res,201,{ok:true,order,requestId})}catch(error){const status=error?.statusCode||500;return sendJson(res,status,{ok:false,error:{code:status===413?'PAYLOAD_TOO_LARGE':'SERVER_ERROR',message:status===413?'Payload too large.':'Unexpected server error.',requestId}})}}return sendJson(res,404,{ok:false,error:{code:'NOT_FOUND',message:'Route not found.',requestId}})});
async function start(){await loadOrders();server.listen(PORT,HOST,()=>console.log(`MOMOHA API listening on http://${HOST}:${PORT}`))}if(process.argv[1]&&process.argv[1].endsWith('/server.mjs'))start();export{server,MENU,validateOrder,start};
