const projects=[
 {name:'DataVac',image:'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=1400&q=85',role:'Frontend · API · Payments · PDF · E2E',tags:['Next.js','TypeScript','API','CloudPayments'],text:'Информационный продукт с каталогом вакцин, поиском, фильтрацией, реальными API, платежным сценарием и PDF.',repo:'https://github.com/DataVac-masterskaya/data-vac-frontend'},
 {name:'Furniture Store',image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1400&q=85',role:'Product UI · Responsive · SEO',tags:['HTML','SCSS','JavaScript','Schema.org'],text:'Премиальный мебельный шоурум с каталогом, фильтрами, заявкой покупателя и демо-кабинетом продавца.',repo:'https://github.com/nestlir/Furniture_Store_Ru'},
 {name:'Stellar Burger',image:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1400&q=85',role:'React · State · Routing · API',tags:['React','Redux','REST API'],text:'Приложение для заказа бургеров с авторизацией, конструктором и личным кабинетом.',repo:'https://github.com/nestlir/stellar-burger'},
 {name:'Mesto',image:'https://images.unsplash.com/photo-1516321165247-4aa89a48be28?auto=format&fit=crop&w=1400&q=85',role:'React state · Forms · REST API',tags:['React','REST API','CSS'],text:'Социальный интерфейс с профилем, карточками, лайками и модальными сценариями.',repo:'https://github.com/nestlir/mesto-project-ff'},
 {name:'Blog Customizer',image:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1400&q=85',role:'State modeling · Forms · Reusable UI',tags:['React','TypeScript','Forms'],text:'Конфигурируемый интерфейс статьи с настройкой визуальных параметров.',repo:'https://github.com/nestlir/blog-customizer'},
 {name:'Оно тебе надо',image:'https://images.unsplash.com/photo-1455885666463-19c48e1a9a39?auto=format&fit=crop&w=1400&q=85',role:'Semantic HTML · Responsive · Visual composition',tags:['HTML','CSS','Responsive'],text:'Editorial landing page с акцентом на типографику, композицию и адаптивность.',repo:'https://github.com/nestlir/ono-tebe-nado'}
];
const grid=document.getElementById('projectGrid'),modal=document.getElementById('modal'),content=document.getElementById('modalContent');
grid.innerHTML=projects.map((p,i)=>`<article class="project"><figure><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="frame">FRAME ${String(i+1).padStart(2,'0')}</span><span class="visual-sticker">✦</span></figure><div class="project-body"><small>${p.role}</small><h3>${p.name} <b>↗</b></h3><p>${p.text}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><button class="open-case" data-index="${i}">Открыть case ↗</button></div></article>`).join('');
function open(i){const p=projects[i];content.innerHTML=`<div class="modal-media"><img src="${p.image}" alt="${p.name}"><span>SELECTED / ${p.name.toUpperCase()}</span></div><div class="modal-copy"><div class="eyebrow">Selected work</div><h2>${p.name}</h2><p class="modal-role">${p.role}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><p>${p.text}</p><div class="system-map"><span>UI</span><i>→</i><span>API</span><i>→</i><span>DATA</span><i>→</i><span>SHIP</span></div><a class="button" href="${p.repo}" target="_blank" rel="noreferrer">Открыть репозиторий ↗</a></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
grid.addEventListener('click',e=>{const b=e.target.closest('[data-index]');if(b)open(Number(b.dataset.index))});document.getElementById('close').addEventListener('click',close);modal.querySelector('.modal-backdrop').addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
let last=0;window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;document.getElementById('progress').style.width=`${max?scrollY/max*100:0}%`;last=scrollY},{passive:true});
const menu=document.getElementById('menu');const nav=document.querySelector('.nav-shell nav');menu.addEventListener('click',()=>{document.body.classList.toggle('menu-open')});
